{"name": "test_case_02", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "def test_case_02():\n>       assert 0\nE       assert 0\n\nscripts\\test_caset_01.py:12: AssertionError"}, "start": 1615541371208, "stop": 1615541371209, "uuid": "04df5619-3232-4a3c-a0d7-d68c1307e8ca", "historyId": "e6b5e854e0ff6e442608c1d48476e849", "testCaseId": "798c5d18d27f4c1d6208a27374552a84", "fullName": "scripts.test_caset_01#test_case_02", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_caset_01"}, {"name": "host", "value": "tian"}, {"name": "thread", "value": "48388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_caset_01"}]}